### ISSUE TITLE
Feature request: displaying only files with less than 100% coverage in the file table

### ISSUE THREAD

**Issue by Lundis** [lucassabreu/comment-coverage-clover#14]
For larger projects with hundreds of files it offers no value to show the files with 100% coverage in the table. I would like to see only the files that I need to take action on.

For example now it outputs:
```
file1.php 100%
file2.php 100%
...
file150.php 0%
...
file300.php 100%
```

I would like to configure it to show only:

```
file150.php 0%
```

**Comment by lucassabreu** [comment]
hi @Lundis i add a new parameter called `table-bellow-coverage` that you can use to achieve that.

**Comment by Lundis** [comment]
Wow thanks for the quick implementation! You made a typo though. It should be "table-below-coverage". (bellow means something else)

**Comment by lucassabreu** [comment]
i fixed the screaming problem hehe, thank you for pointing out
