### ISSUE TITLE
Don't show empty files

### ISSUE THREAD

**Issue by sertxudev** [lucassabreu/comment-coverage-clover#19]
Hi, thanks to this GitHub Action I'm able to review the coverage of my projects.

I was wondering if there's a way to hide the empty files from the report comment.

For example, those four files have no content inside.

![image](https://user-images.githubusercontent.com/22801379/191007207-8f3fb0dd-eba9-4d01-b272-69d1a084ecd0.png)

![image](https://user-images.githubusercontent.com/22801379/191007300-28cedcc7-bd34-4047-a224-e8fe34eba2de.png)

On the other hand, this file has some code but no line is being tested.

![image](https://user-images.githubusercontent.com/22801379/191007433-4c10a489-c3d7-40fd-b36d-798b719b8a7d.png)

![image](https://user-images.githubusercontent.com/22801379/191007498-8e18dea4-202e-4f80-a650-1dc60d087f51.png)

As you can see both examples are shown in the table report.
I'm currently hiding files with more than 95% tested, and I wanted to hide the four files without code.

----

**MergesPdfs.php**

```xml
<file name="/var/www/html/app/Actions/Utilities/MergesPdfs.php">
  <class name="App\Actions\Utilities\MergesPdfs" namespace="global">
    <metrics complexity="2" methods="1" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="10" coveredstatements="0" elements="11" coveredelements="0"/>
  </class>
  <line num="16" type="method" name="mergePdfs" visibility="protected" complexity="2" crap="6" count="0"/>
  <line num="17" type="stmt" count="0"/>
  <line num="19" type="stmt" count="0"/>
  <line num="21" type="stmt" count="0"/>
  <line num="22" type="stmt" count="0"/>
  <line num="25" type="stmt" count="0"/>
  <line num="26" type="stmt" count="0"/>
  <line num="27" type="stmt" count="0"/>
  <line num="28" type="stmt" count="0"/>
  <line num="30" type="stmt" count="0"/>
  <line num="34" type="stmt" count="0"/>
  <metrics loc="37" ncloc="31" classes="1" methods="1" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="10" coveredstatements="0" elements="11" coveredelements="0"/>
</file>
```

**RepositoryNotFoundException.php**

```xml
<file name="/var/www/html/app/Exceptions/RepositoryNotFoundException.php">
  <class name="App\Exceptions\RepositoryNotFoundException" namespace="global">
    <metrics complexity="0" methods="0" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="0" coveredstatements="0" elements="0" coveredelements="0"/>
  </class>
  <metrics loc="11" ncloc="10" classes="0" methods="0" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="0" coveredstatements="0" elements="0" coveredelements="0"/>
</file>
```

Maybe the action could check if the values `classes`, `methods`, `conditionals`, `statements` and/or `elements` are 0, to know if the file is indeed empty.

**Comment by ricklambrechts** [comment]
There is a `only-with-cover` option. Did you try that?

**Comment by lucassabreu** [comment]
hi @sertxudev, just to be sure i understood it, you wanna a option to hide files that have "0 lines" like the `RepositoryNotFoundException` right?

to hide the `MergesPdfs` you can use the `only-with-cover` input.

**Comment by sertxudev** [comment]
Yeah, that's right.

**Comment by lucassabreu** [comment]
@sertxudev i created a new input "only-with-coverable-lines", please take a look if it solves this problem

**Comment by sertxudev** [comment]
Nice work @lucassabreu.

I've checked the `only-with-coverable-lines` input in one of my projects and now the table it's showing 41 files, instead of the 66 shown previously, that's 25 non-coverable files removed from the table.

I'm adding the new input to another four projects. 

Thanks! 😄
