### ISSUE TITLE
Feature Request: Scope for Comments

### ISSUE THREAD

**Issue by Floppy012** [lucassabreu/comment-coverage-clover#32]
Hey 👋🏼 It's me again.

I wanted to request a feature that would come in pretty handy: Scoped PR Comments.

In my organization, we're using monorepos that contain backend and frontend code. They are tested by separate frameworks in separate workflows, and thus generate two different coverage reports. We don't want to combine them because different teams work on Frontend/Backend.

My request is to add a feature that allows to set a scope for the PR comment so that multiple comments per PR are possible. In our case that would be one comment for backend coverage and one for frontend coverage.

**Comment by jacekk** [comment]
@Floppy012 I think you could use `signature` param.

Check out these examples: https://github.com/lucassabreu/comment-coverage-clover/blob/main/.github/workflows/example.yml . Each `signature` creates/updates a separate comment in given PR. Like in here: https://github.com/lucassabreu/comment-coverage-clover/pull/31

**Comment by Floppy012** [comment]
Uh nice. That was what I'm looking for. Thanks
