### ISSUE TITLE
Spelling branchs

### ISSUE THREAD

**Issue by klippx** [lucassabreu/comment-coverage-clover#34]
<img width="604" alt="Screenshot 2023-05-24 at 16 20 54" src="https://github.com/lucassabreu/comment-coverage-clover/assets/2785359/89c647dd-4c72-4664-8047-5d5688fd73cb">

In two different places, both in summary and table heading text.

**Comment by lucassabreu** [comment]
hi @klippx the release v0.9.3 has a fix for that, could you check if it is what you expected?
