### ISSUE TITLE
Exits with `0` exit code and without debug logging to indicate possible issue when no token is available in env

### ISSUE THREAD

**Issue by ermik** [lucassabreu/comment-coverage-clover#43]
The token usage or required scopes are undocumented
https://github.com/lucassabreu/comment-coverage-clover/blob/ec666df65249f2ba5d3c2b3654a85e2912771ec1/src/index.ts#L19

and the returns are not logging anything
https://github.com/lucassabreu/comment-coverage-clover/blob/ec666df65249f2ba5d3c2b3654a85e2912771ec1/src/index.ts#L195-L196

**Comment by lucassabreu** [comment]
hi @ermik i added to the readme the scope, it needs `repo`. but is not required, the default token created by github should sufice.

![Captura de tela de 2023-10-19 10-54-07](https://github.com/lucassabreu/comment-coverage-clover/assets/3457213/b0afcad1-6d59-40f2-802d-b233c08044be)

**Comment by ermik** [comment]
Hey @lucassabreu - appreciate the response. I'm gonna think of what else this can be expanded into. I'm definitely hitting an edge case where nothing is posted even though there's a clover file and a valid token... I think more debug output would be a general point of improvement.

**Comment by lucassabreu** [comment]
if any error happens it will be shown in the logs, github actions ensures that.

could you post the workflow and workflow log @ermik ?
